channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.14.2
  - cloudpickle==3.0.0
  - numpy==1.25.2
  - packaging==24.1
  - pandas==2.0.3
  - psutil==6.0.0
  - pyyaml==6.0.1
  - scikit-learn==1.5.0
  - scipy==1.14.0
  - torch==2.3.1
name: mlflow-env
